os:
  - linux
  - osx

language: c
compiler: gcc

addons:
  apt:
    packages: ['gfortran']

before_install:
   - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update &> /dev/null;
      brew cask uninstall --force oclint;
      brew install gcc || true;
      brew link --overwrite gcc;
    fi

install:
  - make

script:
  - source setup.sh
  - danton
